### PR TITLE
Provide java update version

### PR DESCRIPTION
**Pull request by abellmann**
Hi,

I added the functionality to explicitly set the java version desired (optional). The default behaviour remains unchanged.

Best,
Andreas

### CODE REVIEW

**Comment by tersmitten** [comment]
I don't fully understand the usecase of this. Can you you explain?

**Comment by abellmann** [comment]
Hi,

I want to be in control of the java version I use in my project. If I reprovision my system I don't want to update the java version by accident (i.e. update the java version of my production system without having tested and verified it first) or getting hard to find problems or test failures in my dev/test systems, because I am not aware that the java version was updated "automatically".

I also want to be able to fully reproduce a specific release of my product (i.e. I get a bug in my production system and want to reproduce it with the exact same java version as it is on production)

Andreas

**Comment by tersmitten** [comment]
Ok I understand, I'll have a look at it soon.

**Comment by tersmitten** [comment]
@abellmann Can you fix the conflict so I can test it?

**Pull request merged**
